copy over zsh history

fudgeups:
- commands for symlinks
- cat dotfiles/zshrc >> ~/.zshrc
- install doom!

to install

- shell
  - zsh
    - `sudo apt install zsh`
  - fzf: `sudo apt install fzf` or `brew install fzf`
  - to get ^r to work:
     =git clone https://github.com/joshskidmore/zsh-fzf-history-search.git ~/.zsh/plugins/zsh-fzf-history-search=
- emacs
  - ubuntu:
    #+begin_src sh
sudo snap install emacs --classic
sudo apt install cmake libtool autoconf automake # to compile stuff
sudo apt-get install libtool-bin # to actually have an exec
sudo apt install ripgrep # for doom
sudo apt install xclip # for clipboard stuff
    #+end_src
  - mac:
  =brew tap d12frosted/emacs-plus=
  =brew install emacs-plus@28 --with-native-comp --with-ctags --with-xwidgets=
  https://github.com/d12frosted/homebrew-emacs-plus#install
  - doom (symlink doom.d first!) https://github.com/doomemacs/doomemacs#install
    - PROBLEM: texinfo is old, so maybe do this? =brew ln texinfo --force=
- worknotes https://github.com/kkrausse/worknotes
- sdkman https://sdkman.io/install
- clojure =brew install clojure/tools/clojure=
  #+begin_src bash
  keytool -import -alias netskope -keystore ~/.sdkman/candidates/java/17.0.5-zulu/zulu-17.jdk/Contents/Home/lib/security/cacerts -file /Library/netskope-cert-bundle.pem
  #+end_src

symlinks (run from project root)

#+begin_src bash

# for emacs c source file
git clone --branch emacs-28.2 --depth 1 https://github.com/emacs-mirror/emacs doom.d/repos/emacs

cd dotfiles
ln -s $(pwd)/doom.d/ ~/.doom.d
ln -s $(pwd)/vimrc ~/.vimrc
# nah this is dumb ln -s $(pwd)/zshrc ~/.zshrc

ln -s $(pwd)/gitconfig ~/.gitconfig
# clojure specific
ln -s $(pwd)/lsp ~/.lsp
ln -s $(pwd)/clj-kondo ~/.clj-kondo
ln -s $(pwd)/clojure ~/.clojure
# idk if even needed
ln -s $(pwd)/bin ~/.bin
#+end_src

vim vinegar

#+begin_src bash
mkdir -p ~/.vim/pack/tpope/start/vim-vinegar/
git clone https://github.com/tpope/vim-vinegar.git ~/.vim/pack/tpope/start/vim-vinegar/
#+end_src


install nvm to get node.

need cmake for vterm in emacs:

#+begin_src bash
# for cmake and libtools for vterm
brew install cmake
brew install libtool
# clojure
# make sure you install sdkman and get a java version you like
brew install clojure/tools/clojure
#+end_src



I found this interesting in my `.zshrc.pre-oh-my-zsh`

#+begin_src bash
export PATH=$HOME/bin:$PATH
export PATH=~/bin/just-v0.8.3-x86_64-apple-darwin:$PATH
export JAVA_HOME=$(/usr/libexec/java_home)

# bash completion stuff
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# kubectl use-context shortcut with autocomplete
kuc() {
  if [ $# -ne 1 ]; then
    echo "Usage: kuc CONTEXT"
  else
    kubectl config use-context $1
  fi
}
_kuc() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=( $(compgen -W "data-services.us-west-2a pro-apps.us-west-2a pro-apps.us-west-2b pro-apps.eu-central-1b pro-apps.eu-central-1c pro-apps.ap-southeast-1b.prod.pages pro-apps.ap-southeast-1c.prod.pages consumer-apps.us-west-2a consumer-apps.us-west-2b" -- $cur) )
}

complete -F _kuc kuc
#+end_src

* mac setup

** access to git / github to clone this
  - install mac dev tools
** vim
# vim vinegar
mkdir -p ~/.vim/pack/tpope/start/vim-vinegar/
git clone https://github.com/tpope/vim-vinegar.git ~/.vim/pack/tpope/start/vim-vinegar/

cd dotfiles
ln -s $(pwd)/doom.d/ ~/.doom.d
ln -s $(pwd)/vimrc ~/.vimrc

- install homebrew
- install https://github.com/ohmyzsh/ohmyzsh/
  - =git clone https://github.com/joshskidmore/zsh-fzf-history-search.git ~/.zsh/plugins/zsh-fzf-history-search=
  - requires =brew install fzf=
  - =echo "source $(pwd)/zshrc" >> ~/.zshrc=
** install emacs
  
  see https://github.com/d12frosted/homebrew-emacs-plus#install

  =brew tap d12frosted/emacs-plus=
  =brew install emacs-plus@30 --with-ctags --with-xwidgets=
note, default native comp

doom
  - doom (symlink doom.d first!) https://github.com/doomemacs/doomemacs#install
    - =ln -s $(pwd)/doom.d/ ~/.doom.d=
    - PROBLEM: texinfo is old, so maybe do this? =brew ln texinfo --force=


old shsh
#+begin_src sh

# for emacs c source file
git clone --branch emacs-28.2 --depth 1 https://github.com/emacs-mirror/emacs doom.d/repos/emacs

# vim vinegar
mkdir -p ~/.vim/pack/tpope/start/vim-vinegar/
git clone https://github.com/tpope/vim-vinegar.git ~/.vim/pack/tpope/start/vim-vinegar/


cd dotfiles
ln -s $(pwd)/doom.d/ ~/.doom.d
ln -s $(pwd)/vimrc ~/.vimrc

# nah this is dumb ln -s $(pwd)/zshrc ~/.zshrc -- instead:
echo "source $(pwd)/zshrc" >> ~/.zshrc

ln -s $(pwd)/gitconfig ~/.gitconfig
# clojure specific
ln -s $(pwd)/lsp ~/.lsp
ln -s $(pwd)/clj-kondo ~/.clj-kondo
ln -s $(pwd)/clojure ~/.clojure
# idk if even needed
ln -s $(pwd)/bin ~/.bin
#+end_src
